"""Renderer for the dynamic Restorix agent install.sh script.

The INSTALL_TEMPLATE is a Python raw string consumed by `str.format()`.
The ONLY Python placeholders are `{restorix_url}` and `{version}`.
Every other `${...}` is bash variable expansion and MUST stay literal — that's
why every bash brace is doubled (`{{` / `}}`) to escape the format() pass.

Why not Jinja: bash uses `${VAR}` heavily, which would collide with Jinja2
default delimiters. `str.format()` with `{{` escaping is simpler and safer here.
"""

INSTALL_TEMPLATE = r"""#!/usr/bin/env bash
set -euo pipefail

# Restorix Agent Installer (auto-generated by backend at {restorix_url})
# Usage: curl -sSL {restorix_url}/api/v1/agent/install-script | bash -s -- --token=TOKEN_HERE

AGENT_VERSION="{version}"
RESTORIX_URL="{restorix_url}"
PLATFORM_URL="{restorix_url}"
INSTALL_DIR="/opt/dbshield-agent"
CONFIG_DIR="/etc/dbshield-agent"
SERVICE_NAME="dbshield-agent"
AGENT_USER="dbshield"
LOG_DIR="/var/log/dbshield-agent"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()    {{ echo -e "${{BLUE}}[INFO]${{NC}} $*"; }}
success() {{ echo -e "${{GREEN}}[OK]${{NC}} $*"; }}
warn()    {{ echo -e "${{YELLOW}}[WARN]${{NC}} $*"; }}
error()   {{ echo -e "${{RED}}[ERROR]${{NC}} $*"; exit 1; }}

TOKEN=""
for arg in "$@"; do
    case $arg in
        --token=*) TOKEN="${{arg#*=}}" ;;
        --token)   shift; TOKEN="$1" ;;
    esac
done

[ -z "$TOKEN" ] && error "Missing --token argument. Get your token from the Restorix dashboard."
[ "$EUID" -ne 0 ] && error "This script must be run as root"

info "Restorix Agent v${{AGENT_VERSION}} installer"
info "Platform: ${{RESTORIX_URL}}"

if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS_ID="${{ID}}"
    OS_VERSION="${{VERSION_ID:-}}"
else
    OS_ID="unknown"
fi
info "Detected OS: ${{OS_ID}} ${{OS_VERSION}}"

PYTHON_CMD=""
install_python() {{
    for candidate in python3.12 python3.11 python3.10; do
        if command -v "$candidate" &>/dev/null; then
            PYTHON_CMD="$candidate"
            info "Python found: $($candidate --version 2>&1)"
            return 0
        fi
    done
    if command -v python3 &>/dev/null; then
        PY_VER=$(python3 -c 'import sys; print(sys.version_info.minor)')
        PY_MAJ=$(python3 -c 'import sys; print(sys.version_info.major)')
        if [ "$PY_MAJ" -eq 3 ] && [ "$PY_VER" -ge 10 ]; then
            PYTHON_CMD="python3"
            info "Python found: $(python3 --version 2>&1)"
            return 0
        fi
    fi
    case "${{OS_ID}}" in
        ubuntu|debian)
            apt-get update -qq
            apt-get install -y -qq software-properties-common
            add-apt-repository -y ppa:deadsnakes/ppa
            apt-get update -y
            apt-get install -y python3.11 python3.11-venv python3.11-distutils && PYTHON_CMD="python3.11" \
                || (apt-get install -y python3.10 python3.10-venv python3.10-distutils && PYTHON_CMD="python3.10") \
                || error "Cannot install Python 3.10/3.11"
            ;;
        centos|rhel|rocky|almalinux|fedora)
            (yum install -y python3.11 || dnf install -y python3.11) && PYTHON_CMD="python3.11"
            ;;
        *)
            error "Unsupported OS: ${{OS_ID}}. Install Python 3.10+ manually and re-run." ;;
    esac
    success "Python installed: $($PYTHON_CMD --version 2>&1)"
}}
install_python

if ! "$PYTHON_CMD" -m pip --version &>/dev/null; then
    info "Installing pip..."
    curl -sSL https://bootstrap.pypa.io/get-pip.py | "$PYTHON_CMD" -
fi

if ! id "${{AGENT_USER}}" &>/dev/null; then
    info "Creating service user '${{AGENT_USER}}'..."
    useradd --system --no-create-home --shell /usr/sbin/nologin "${{AGENT_USER}}"
fi

if id mssql &>/dev/null; then
    info "Local SQL Server detected - sharing backup directory with mssql user"
    usermod -a -G mssql "${{AGENT_USER}}" 2>/dev/null || true
    TEMP_DIR="/var/opt/mssql/backups/dbshield"
    mkdir -p "${{TEMP_DIR}}"
    chown mssql:mssql "${{TEMP_DIR}}"
    chmod 770 "${{TEMP_DIR}}"
else
    TEMP_DIR="/tmp/dbshield"
    mkdir -p "${{TEMP_DIR}}"
    chown "${{AGENT_USER}}:${{AGENT_USER}}" "${{TEMP_DIR}}"
fi

mkdir -p "${{INSTALL_DIR}}" "${{CONFIG_DIR}}" "${{LOG_DIR}}"
chown "${{AGENT_USER}}:${{AGENT_USER}}" "${{LOG_DIR}}"

if ! "$PYTHON_CMD" -c "import ensurepip" >/dev/null 2>&1; then
    PY_MINOR=$("$PYTHON_CMD" -c "import sys; print('%d.%d' % sys.version_info[:2])")
    apt-get install -y -qq "python${{PY_MINOR}}-venv" 2>/dev/null \
        || apt-get install -y -qq python3-venv python3-full || true
fi

info "Creating Python virtual environment at ${{INSTALL_DIR}}..."
"$PYTHON_CMD" -m venv "${{INSTALL_DIR}}/venv"
"${{INSTALL_DIR}}/venv/bin/pip" install --quiet --upgrade pip
"${{INSTALL_DIR}}/venv/bin/pip" install --quiet requests boto3 paramiko cryptography

info "Downloading agent package..."
AGENT_PKG_URL="${{RESTORIX_URL}}/agent/dbshield-agent-${{AGENT_VERSION}}.tar.gz"
AGENT_PKG="/tmp/dbshield-agent-${{AGENT_VERSION}}.tar.gz"
curl -sSLf -o "${{AGENT_PKG}}" "${{AGENT_PKG_URL}}" \
    || error "Cannot download ${{AGENT_PKG_URL}}"
"${{INSTALL_DIR}}/venv/bin/pip" install --quiet "${{AGENT_PKG}}"
rm -f "${{AGENT_PKG}}"
success "Agent package installed"

info "Writing configuration to ${{CONFIG_DIR}}/config.json..."
cat > "${{CONFIG_DIR}}/config.json" << CONFIGEOF
{{
  "api_url": "${{RESTORIX_URL}}",
  "agent_token": "${{TOKEN}}",
  "poll_interval_seconds": 30,
  "log_level": "INFO",
  "temp_dir": "${{TEMP_DIR}}"
}}
CONFIGEOF
chmod 640 "${{CONFIG_DIR}}/config.json"
chown root:"${{AGENT_USER}}" "${{CONFIG_DIR}}/config.json"

info "Creating systemd service..."
cat > "/etc/systemd/system/${{SERVICE_NAME}}.service" << SERVICEEOF
[Unit]
Description=Restorix Backup Agent
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=${{AGENT_USER}}
Group=${{AGENT_USER}}
ExecStart=${{INSTALL_DIR}}/venv/bin/dbshield-agent
Environment=DBSHIELD_CONFIG=${{CONFIG_DIR}}/config.json
Restart=always
RestartSec=10
StandardOutput=append:${{LOG_DIR}}/agent.log
StandardError=append:${{LOG_DIR}}/agent.log

[Install]
WantedBy=multi-user.target
SERVICEEOF

systemctl daemon-reload
systemctl enable "${{SERVICE_NAME}}"
systemctl restart "${{SERVICE_NAME}}"

sleep 2
if systemctl is-active --quiet "${{SERVICE_NAME}}"; then
    success "Restorix Agent is running!"
else
    warn "Agent service did not start. Check: journalctl -u ${{SERVICE_NAME}} -n 30"
fi

echo
success "Installation complete!"
echo "  Token:    ${{TOKEN}}"
echo "  Platform: ${{RESTORIX_URL}}"
echo "  Config:   ${{CONFIG_DIR}}/config.json"
echo "  Logs:     ${{LOG_DIR}}/agent.log"
"""


import re

_ENDPOINT_RE = re.compile(r'^https?://[a-zA-Z0-9.\-]+(:\d+)?(/.*)?$')
_VERSION_RE = re.compile(r'^[A-Za-z0-9.\-_]{1,50}$')


def render_install_script(agent_endpoint: str, version: str) -> str:
    """Render the install.sh script with the given canonical endpoint + version.

    Validazione paranoica per evitare injection in bash template:
    - agent_endpoint: solo http(s)://host[:port][/path], niente newline/quote/dollar/backtick
    - version: alfanumerici + .-_
    """
    if not _ENDPOINT_RE.match(agent_endpoint or ""):
        raise ValueError(f"agent_endpoint formato non valido: {agent_endpoint!r}")
    if any(c in agent_endpoint for c in '\n\r\t "\'\\${}`'):
        raise ValueError("agent_endpoint contiene caratteri non permessi")
    if not _VERSION_RE.match(version or ""):
        raise ValueError(f"version formato non valido: {version!r}")
    endpoint = agent_endpoint.rstrip("/")
    return INSTALL_TEMPLATE.format(restorix_url=endpoint, version=version)


# ---------------------------------------------------------------------------
# Windows installer (PowerShell)
# ---------------------------------------------------------------------------
# Bootstrap minimale: scarica il tarball agent (che contiene il vero install.ps1)
# e lo esegue. Placeholders Python: {restorix_url} e {version}.
# Tutte le `{` `}` di PowerShell (script blocks, hashtable, subexpressions) sono
# raddoppiate per sopravvivere a str.format().

INSTALL_TEMPLATE_WINDOWS = r"""# Restorix Backup Agent installer for Windows
# Server: {restorix_url}
# Agent version: {version}
#
# Usage:
#   $Env:AGENT_TOKEN = "your-token-here"
#   irm {restorix_url}/api/v1/agent/install-script-windows | iex

#Requires -RunAsAdministrator
#Requires -Version 5.1

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$Token = $env:AGENT_TOKEN
$RestorixUrl = "{restorix_url}"
$Version = "{version}"

if (-not $Token) {{
  Write-Error "AGENT_TOKEN environment variable required. Set: `$Env:AGENT_TOKEN = 'your-token'"
  exit 1
}}

Write-Host "[1/2] Downloading installer script v$Version..."
$TmpDir = Join-Path $env:TEMP ("dbshield-install-" + [System.Guid]::NewGuid().ToString())
New-Item -ItemType Directory -Path $TmpDir -Force | Out-Null
$TarballPath = Join-Path $TmpDir "agent.tar.gz"

$DownloadUrl = "$RestorixUrl/api/v1/agent/download/$Version" + "?token=$Token"
try {{
    Invoke-WebRequest -Uri $DownloadUrl -OutFile $TarballPath -UseBasicParsing
}} catch {{
    Write-Error "Failed to download agent tarball: $_"
    exit 1
}}

# Estrai con tar nativo (disponibile su Windows 10/11 e Server 2019+)
tar -xzf $TarballPath -C $TmpDir
$InstallScript = Join-Path $TmpDir "install.ps1"
if (-not (Test-Path $InstallScript)) {{
    Write-Error "install.ps1 not found in agent tarball v$Version"
    exit 1
}}

Write-Host "[2/2] Running installer..."
& powershell -ExecutionPolicy Bypass -File $InstallScript -Token $Token -RestorixUrl $RestorixUrl -Version $Version

# Cleanup
Remove-Item -Recurse -Force $TmpDir -ErrorAction SilentlyContinue
"""


def render_install_script_windows(agent_endpoint: str, version: str) -> str:
    """Render the install.ps1 bootstrap one-liner for Windows.

    Lo script scaricato e' un bootstrap minimale che a sua volta scarica
    il tarball agent (contenente install.ps1 completo) e lo esegue.

    Validazione paranoica identica a quella Linux per evitare injection.
    """
    if not _ENDPOINT_RE.match(agent_endpoint or ""):
        raise ValueError(f"agent_endpoint formato non valido: {agent_endpoint!r}")
    if any(c in agent_endpoint for c in '\n\r\t "\'\\${}`'):
        raise ValueError("agent_endpoint contiene caratteri non permessi")
    if not _VERSION_RE.match(version or ""):
        raise ValueError(f"version formato non valido: {version!r}")
    endpoint = agent_endpoint.rstrip("/")
    return INSTALL_TEMPLATE_WINDOWS.format(restorix_url=endpoint, version=version)
